image: node:14.19.1-stretch
  
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  script:
   - npm install
   - npm build
   - npm test

pages:
  stage: deploy
  script:
    - npm run-script compile
    - cd frontend/
    - npm install
    - npm run-script build -- --output-path=../public
  when: always
  artifacts:
    paths:
    - public
  only:
  - master
